added requires permission to fix lint:
 /home/runner/work/CrowdLink/CrowdLink/app/src/main/java/com/fyp/crowdlink/data/p2p/WifiDirectManager.kt:109: Error: Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with checkPermission) or explicitly handle a potential SecurityException [MissingPermission]
                  manager.addLocalService(channel, serviceInfo, object : WifiP2pManager.ActionListener {